links: 
  - 'https://drive.google.com/file/d/1WFqpQXzzmDZO-Dyos2QSPoF1Lz54P-JJ/view?usp=share_link'
  - 'https://drive.google.com/file/d/16zvVSmAE3EheGFoUCqsq2hQYS_YQBQcB/view?usp=share_link'
  - 'https://drive.google.com/file/d/1_os7AbH5xJpHlWF4ekZ1zWG6C1knKkTX/view?usp=share_link'
  - 'https://drive.google.com/file/d/1p4bXfiBNV3YugAK5UnA__ZfO3oXWZXwU/view?usp=share_link'

outputs: 
  - '/home/ldonatti/teste/data/01_03_22.csv'
  - '/home/ldonatti/teste/data/04_06_22.csv'
  - '/home/ldonatti/teste/data/07_12_22.csv'
  - '/home/ldonatti/teste/data/temperatura.csv'
      
search_columns:
  - 'Data'
  - 'Hora UTC'
  - 'TEMPERATURA DO AR'
  - 'UMIDADE RELATIVA'
  - 'PRECIPITAÇÃO'

column_to_forecast: 'ETC - Energia consumida (kWh)'
#column_to_forecast: 'SA - Potência aparente na fase A (VA)'

time_features:
  - 'hour'
  - 'dayofweek'
  - 'quarter'
  - 'month'
  - 'dayofmonth'

categorical_columns: 
  - 'hour'
  - 'dayofweek'
  - 'quarter'
  - 'dayofmonth'

numerical_columns: 
  - 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'
  - 'UMIDADE RELATIVA DO AR, HORARIA (%)'
  - 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)'

n_input: 24
n_out: 24